# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
nav:
  - 主页: 'index.md'
  - 目录:
    - 课程介绍: '00 about the course.md'
    - 基础篇:
      - 01 开发环境搭建: '01 setup the development environment.md'
      - 02 hello Widget: '02 hello Widget.md'
      - 03 关于OpenGL: '03 about OpenGL.md'
      - 04 Hello Triangle: '04 hello Triangle.md'
      - 05 坐标系统: '05 coordinate system.md'
      - 06 添加相机: '06 add camera.md'
      - 07 相机原理: '07 principle of camera.md'
      - 08 关于vcpkg的使用: '08 use of vcpkg.md'
    - 场景搭建:
      - 09 默认工作平面: '09 draw default work plane.md'
      - 10 添加视图立方体: '10 add view cube.md'
      - 11 添加旋转中心标识: '11 add label of rotate center.md'
      - 12 UI：添加工具栏按钮: '12 UI - add toolBar button.md'
    - 交互和绘制:
      - 13 介绍框架体系并绘制线: '13 draw line and intro of framework system.md'
      - 14 其它类型线的绘制: '14 draw curve.md'
      - 15 图片绘制: '15 draw image.md'
      - 16 添加捕捉吸附标识: '16 add snap label.md'
    - 操作和设置:
      - 17 添加一些组件: '17 add some components to scene.md'
      - 18 选中效果: '18 selected effect.md'
      - 19 设置工作平面: '19 set work plane.md'
      - 20 框选选择: '20 box select.md'
      - 21 复制: '21 copy.md'
      - 22 删除: '22 delete.md'
      - 23 显隐控制: '23 show and hide controls.md'
      - 24 图层管理: '24 layer management.md'
      - 25 线框模式: '25 wire frame mode.md'
    - IO和其它:
      - 26 关于: '26 about.md'
      - 27 文件打开和保存: '27 file open and save.md'
      - 28 其它事项: '28 other matters.md'
  - 课程代码: 'code_repo.md'
  - CGLib: 'intro.md'

site_name: 'Computer Graphics'

site_description: '计算机图形学课程'

site_url: https://hashixuehua.github.io/geometry/

repo_url: https://github.com/hashixuehua/geometry

markdown_extensions:
  - admonition
  - smarty
  - sane_lists
  - mdx_math

extra_javascript:
  - 'mathjax/MathJax.js?config=TeX-AMS_HTML'

extra_css:
  - css/style.css
  - css/admonition_fix.css

docs_dir: 'docs'

theme:
    name: null
    custom_dir: 'yeti'
