# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
nav:
  - 主页: 'index.md'
  - 目录:
    - 课程介绍: '00 about the course.md'
    - 基础篇:
      - 开发环境搭建: '01 setup the development environment.md'
      - hello Widget: '02 hello Widget.md'
      - 关于OpenGL: '03 about OpenGL.md'
      - Hello Triangle: '04 hello Triangle.md'
      - 坐标系统: '05 coordinate system.md'
      - 相机: '06 camera.md'
      - 补充：关于vcpkg的使用: '06 (supplement)use of vcpkg.md'
    - 场景搭建:
      - 默认工作平面: '07 draw default work plane.md'
      - 添加视图立方体: '08 add view cube.md'
      - 添加旋转中心标识: '09 add label of rotate center.md'
      - UI：添加工具栏按钮: '10 UI - add toolBar button.md'
    - 交互和绘制:
      - 介绍框架体系并绘制线: '11 draw line and intro of framework system.md'
      - 其它类型线的绘制: '12 draw curve.md'
      - 图片绘制: '13 draw image.md'
      - 添加捕捉吸附标识: '14 add snap label.md'
    - 操作和设置:
      - 添加一些组件: '15 add some components to scene.md'
      - 选中效果: '16 selected effect.md'
      - 设置工作平面: '17 set work plane.md'
      - 框选选择: '18 box select.md'
      - 复制: '19 copy.md'
      - 删除: '20 delete.md'
      - 显隐控制: '21 show and hide controls.md'
      - 图层管理: '22 layer management.md'
      - 线框模式: '23 wire frame mode.md'
    - IO和其它:
      - 关于: '24 about.md'
      - 文件打开和保存: '25 file open and save.md'
      - 其它事项: '26 other matters.md'
  - 课程代码: 'code_repo.md'
  - CGLib: 'intro.md'

site_name: 'Computer Graphics'

site_description: '计算机图形学课程'

site_url: https://hashixuehua.github.io/geometry/

repo_url: https://github.com/hashixuehua/geometry

markdown_extensions:
  - admonition
  - smarty
  - sane_lists
  - mdx_math

extra_javascript:
  - 'mathjax/MathJax.js?config=TeX-AMS_HTML'

extra_css:
  - css/style.css
  - css/admonition_fix.css

docs_dir: 'docs'

theme:
    name: null
    custom_dir: 'yeti'
